### ISSUE TITLE
[Validator] update types

### ISSUE THREAD

**Issue by wan2land** [Wandu/Framework#15]
- File..
  - [ ] File Type - Mime
  - [ ] File Type - Extension
  - [ ] File Size
- [ ] Card (Number, Expiry, .. )
- [ ] Length
- [ ] DateTime (with format like Y-m-d)

**Comment by webhacking** [comment]
Can i join this issue ?

**Comment by wan2land** [comment]
of course.

master(4.0-beta) branch and 3.0 branch are very different. please note this only.
it doent matter whether PL master or 3.0. :-)

ref.

- [master's tester](https://github.com/Wandu/Framework/tree/master/src/Wandu/Validator/Testers)
- [3.0's rule](https://github.com/Wandu/Framework/tree/3.0/src/Wandu/Validator/Rules)

**Comment by webhacking** [comment]
@wan2land Got it.
Why don't we make slack channel to share the progress of the project?

**Comment by wan2land** [comment]
just 2 people only......................... but, i make it!

check README.md :-) Thank you
